name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_shell_escape: true
      
      - name: Rename PDF file
        run: mv main.pdf ap-cs-principles-summary.pdf
      
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: AP-CSP-Summary
          path: ap-cs-principles-summary.pdf
          
      # Create Release (only on tags)
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ap-cs-principles-summary.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }} 